{
 "4.0.8": {
  "meta": {
   "description": "Exception interfaces and implementations",
   "homepage": "https://pypi.python.org/pypi/zope.exceptions",
   "license": {
    "fullName": "Zope Public License 2.0",
    "shortName": "zpl20",
    "spdxId": "ZPL-2.0",
    "url": "http://spdx.org/licenses/ZPL-2.0.html"
   },
   "long_description": "",
   "maintainers": [
    {
     "email": "cillian.deroiste@gmail.com",
     "github": "cillianderoiste",
     "name": "Cillian de R\u00f3iste"
    }
   ],
   "name": "python3.6-zope.exceptions",
   "platforms": [
    {
     "kernel": {
      "_type": "kernel",
      "execFormat": {
       "_type": "exec-format",
       "name": "elf"
      },
      "families": {},
      "name": "linux"
     }
    },
    {
     "kernel": {
      "families": {
       "darwin": {
        "_type": "exec-format",
        "name": "darwin"
       }
      }
     }
    }
   ],
   "position": "pkgs/top-level/python-packages.nix:15395"
  },
  "revs": [
   "000482ffc470f798fb3aa1673b39a38680cbb567",
   "036164bd637d848620e20786e86cf9d8e902a9db"
  ]
 }
}